name: PR Integration Test

on: pull_request

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: gardenlinux/workflow-telemetry-action@v2
        with:
          comment_on_pr: false
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Merge with latest main
        uses: ./.github/actions/merge
      - uses: actions/setup-node@v4
        name: Setup node
        with:
          node-version: 22
      - name: 'Install dependencies'
        run: npm ci
      - name: 'Build application'
        run: npm run build
      - name: 'Run preview'
        run: npm run preview &
      - name: 'Install test dependencies'
        run: (cd tests && npm ci)
      - name: Run integration tests
        run: (cd tests && npm run test)
      - name: Uploads artifacts
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: cypress-${{ github.job }}
          path: tests/cypress/
