name: Unit tests
on: pull_request
jobs:
  run-unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout under $GITHUB_WORKSPACE
        uses: actions/checkout@v3
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install all dependencies
        run: npm install
      - name: Run Unit Tests
        run: npm run test
